{
 "title": "02 - Threads",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_stream_application{cluster_type=\"streams\"}, job)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_stream_application{job=~\"${job}\", application_id=~\".+\"}, application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_stream_application{cluster_type=\"streams\", job=~\"${job}\", application_id=~\"$application\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_stream_processor_node_process_rate{job=~\"$job\", instance=~\"$instance\"}, thread_id)"
    }
   },
   { "name": "measurement", "query": "commit,poll,process,punctuate" }
  ]
 },
 "panels": [
  {
   "title": "${measurement} total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "total ops" } },
   "targets": [
    {
     "expr": "sum without(job,instance,thread) (kafka_stream_thread_${measurement}_total{job=~\"${job}\", instance=~\"${instance}\", thread_id=~\"${thread}\"} * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "total ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_stream_thread_${measurement}_total{job=~\"${job}\", instance=~\"${instance}\", thread_id=~\"${thread}\"} * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum without(job,instance,thread) (kafka_stream_thread_${measurement}_rate{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"} * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kafka_stream_thread_${measurement}_rate{job=~\"${job}\", instance=~\"${instance}\", thread_id=~\"${thread}\"} * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate (grafana computed)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum without(job,instance,thread) (rate(kafka_stream_thread_${measurement}_total{thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"}[$__rate_interval]) * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate (grafana computed)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(kafka_stream_thread_${measurement}_total{thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"}[$__rate_interval]) * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(job,instance,thread) (((kafka_stream_thread_${measurement}_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"}) >=0) * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} ratio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (((kafka_stream_thread_${measurement}_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"}) >=0)  * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without(job,instance,thread) (kafka_stream_thread_${measurement}_latency_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"} * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (kafka_stream_thread_${measurement}_latency_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"} * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "records ${measurement} / iteration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "avg without(job,instance,thread) (kafka_stream_thread_${measurement}_records_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"} * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "records ${measurement} / iteration (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (kafka_stream_thread_${measurement}_records_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", job=~\"${job}\"} * on (job, instance) group_left(application_id) kafka_stream_application{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  }
 ]
}